title: Promoting Student Success through Online Learning
description: UCLA Library teaches critical information skills everywhere learning happens.
sitename: Promoting Student Success
baseurl: '/learning-everywhere'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME